package io.github.iuin8.remote

import java.io.File

/**
 * SSH 配置管理工具
 * 负责自动将项目的 SSH 配置注入到系统配置中
 */
object SshConfigManager {
    
    private const val PLUGIN_INCLUDE_LINE = "Include ~/.ssh/gradle/remote-plugin/*"
    private const val PLUGIN_COMMENT_START = "# Auto-generated by Gradle Remote Plugin"
    private const val PLUGIN_COMMENT_WARN = "# DO NOT EDIT THIS BLOCK MANUALLY"
    
    private const val MANAGED_CONFIG_HEADER = "# Gradle Remote Plugin - Managed SSH Configurations"
    private const val MANAGED_CONFIG_NOTE = "# This file is auto-generated and managed by the plugin"
    
    /**
     * 设置项目的 SSH 配置
     * 
     * @param projectRootDir 项目根目录
     * @param projectName 项目名称
     */
    fun setupSshConfig(projectRootDir: File, projectName: String) {
        try {
            // 检查项目的 SSH 配置文件是否存在
            val projectSshConfig = File(projectRootDir, "gradle/remote-plugin/.ssh/config")
            if (!projectSshConfig.exists()) {
                println("[remote-plugin] 项目未配置 SSH 配置文件，跳过 SSH 配置注入")
                return
            }
            
            println("[remote-plugin] 找到 SSH 配置文件：gradle/remote-plugin/.ssh/config")
            
            // 第一步：确保系统配置包含插件 Include
            ensureSystemConfigIncludesPlugin()
            
            // 第二步：确保插件管理配置包含当前项目
            ensureManagedConfigIncludesProject(projectRootDir, projectName, projectSshConfig)
            
        } catch (e: Exception) {
            println("[remote-plugin] [WARN] 无法注入 SSH 配置，原因：${e.message}")
        }
    }
    
    /**
     * 确保系统 ~/.ssh/config 包含插件的 Include 指令
     */
    private fun ensureSystemConfigIncludesPlugin() {
        val userHome = System.getProperty("user.home")
        val sshDir = File(userHome, ".ssh")
        val systemConfig = File(sshDir, "config")
        
        // 确保 .ssh 目录存在
        if (!sshDir.exists()) {
            sshDir.mkdirs()
            sshDir.setReadable(false, false)
            sshDir.setReadable(true, true)
            sshDir.setWritable(false, false)
            sshDir.setWritable(true, true)
            sshDir.setExecutable(false, false)
            sshDir.setExecutable(true, true)
        }
        
        // 如果系统配置不存在，创建它
        if (!systemConfig.exists()) {
            systemConfig.createNewFile()
            systemConfig.setReadable(false, false)
            systemConfig.setReadable(true, true)
            systemConfig.setWritable(false, false)
            systemConfig.setWritable(true, true)
        }
        
        // 读取现有配置
        val existingContent = if (systemConfig.exists()) {
            systemConfig.readText()
        } else {
            ""
        }
        
        // 检查是否已包含插件 Include 指令
        if (existingContent.lines().any { it.trim() == PLUGIN_INCLUDE_LINE.trim() }) {
            println("[remote-plugin] 系统 SSH 配置已包含 Gradle Remote Plugin 引用")
            return
        }
        
        // 在文件开头插入插件 Include 块
        val pluginBlock = buildString {
            appendLine(PLUGIN_COMMENT_START)
            appendLine(PLUGIN_COMMENT_WARN)
            appendLine(PLUGIN_INCLUDE_LINE)
            appendLine()
        }
        
        val newContent = pluginBlock + existingContent
        
        // 写入配置（通过临时文件确保原子性）
        val tempFile = File(systemConfig.parentFile, "${systemConfig.name}.tmp")
        try {
            tempFile.writeText(newContent)
            tempFile.setReadable(false, false)
            tempFile.setReadable(true, true)
            tempFile.setWritable(false, false)
            tempFile.setWritable(true, true)
            
            // 替换原文件
            tempFile.renameTo(systemConfig)
            println("[remote-plugin] 已将 Gradle Remote Plugin 配置引用注入到 ~/.ssh/config")
        } finally {
            if (tempFile.exists()) {
                tempFile.delete()
            }
        }
    }
    
    /**
     * 确保插件管理配置包含当前项目
     */
    private fun ensureManagedConfigIncludesProject(
        projectRootDir: File,
        projectName: String,
        projectSshConfig: File
    ) {
        val userHome = System.getProperty("user.home")
        val pluginConfigDir = File(userHome, ".ssh/gradle/remote-plugin")
        val managedConfig = File(pluginConfigDir, "config")
        
        // 确保插件配置目录存在
        if (!pluginConfigDir.exists()) {
            pluginConfigDir.mkdirs()
            pluginConfigDir.setReadable(false, false)
            pluginConfigDir.setReadable(true, true)
            pluginConfigDir.setWritable(false, false)
            pluginConfigDir.setWritable(true, true)
            pluginConfigDir.setExecutable(false, false)
            pluginConfigDir.setExecutable(true, true)
        }
        
        val projectIncludeLine = "Include ${projectSshConfig.absolutePath}"
        
        // 读取现有配置
        val existingContent = if (managedConfig.exists()) {
            managedConfig.readText()
        } else {
            ""
        }
        
        // 检查是否已包含当前项目
        if (existingContent.lines().any { it.trim() == projectIncludeLine.trim() }) {
            println("[remote-plugin] 插件管理配置已包含当前项目，跳过注入")
            return
        }
        
        // 构建新的配置块
        val projectBlock = buildString {
            // 如果文件为空，添加文件头
            if (existingContent.isEmpty()) {
                appendLine(MANAGED_CONFIG_HEADER)
                appendLine(MANAGED_CONFIG_NOTE)
                appendLine()
            } else if (existingContent.isNotBlank()) {
                // 如果已有内容，先添加空行
                appendLine()
            }
            
            // 添加项目注释和 Include 指令
            appendLine("# Project: $projectName")
            appendLine("# Path: ${projectRootDir.absolutePath}")
            appendLine(projectIncludeLine)
        }
        
        val newContent = existingContent + projectBlock
        
        // 写入配置（通过临时文件确保原子性）
        val tempFile = File(managedConfig.parentFile, "${managedConfig.name}.tmp")
        try {
            tempFile.writeText(newContent)
            tempFile.setReadable(false, false)
            tempFile.setReadable(true, true)
            tempFile.setWritable(false, false)
            tempFile.setWritable(true, true)
            
            // 替换原文件
            tempFile.renameTo(managedConfig)
            println("[remote-plugin] 已将项目 SSH 配置添加到插件管理配置中")
        } finally {
            if (tempFile.exists()) {
                tempFile.delete()
            }
        }
    }
}
