package io.github.iuin8.remote

import java.io.File

/**
 * SSH 配置管理工具
 * 负责自动将项目的 SSH 配置注入到系统配置中
 */
object SshConfigManager {
    
    private const val PLUGIN_INCLUDE_LINE = "Include ~/.ssh/gradle/remote-plugin/*"
    private const val PLUGIN_COMMENT_START = "# Auto-generated by Gradle Remote Plugin"
    private const val PLUGIN_COMMENT_WARN = "# DO NOT EDIT THIS BLOCK MANUALLY"
    
    private const val MANAGED_CONFIG_HEADER = "# Gradle Remote Plugin - Managed SSH Configurations"
    private const val MANAGED_CONFIG_NOTE = "# This file is auto-generated and managed by the plugin"
    
    /**
     * 设置项目的 SSH 配置
     * 
     * @param projectRootDir 项目根目录
     * @param projectName 项目名称
     */
    fun setupSshConfig(projectRootDir: File, projectName: String) {
        try {
            // 检查项目的 SSH 配置文件是否存在
            val projectSshConfig = File(projectRootDir, "gradle/remote-plugin/.ssh/config.template")
            if (!projectSshConfig.exists()) {
                println("[remote-plugin] 项目未配置 SSH 配置文件，跳过 SSH 配置注入")
                return
            }
            
            println("[remote-plugin] 找到 SSH 配置文件：gradle/remote-plugin/.ssh/config.template")
            
            // 第一步：确保系统配置包含插件 Include
            ensureSystemConfigIncludesPlugin()
            
            // 第二步：确保插件管理配置包含当前项目
            ensureManagedConfigIncludesProject(projectRootDir, projectName, projectSshConfig)
            
        } catch (e: Exception) {
            println("[remote-plugin] [WARN] 无法注入 SSH 配置，原因：${e.message}")
        }
    }
    
    /**
     * 确保系统 ~/.ssh/config 包含插件的 Include 指令
     */
    private fun ensureSystemConfigIncludesPlugin() {
        val userHome = System.getProperty("user.home")
        val sshDir = File(userHome, ".ssh")
        val systemConfig = File(sshDir, "config")
        
        ensureSshDirAndConfigExists(sshDir, systemConfig)
        
        val existingContent = systemConfig.readText()
        if (existingContent.lines().any { it.trim() == PLUGIN_INCLUDE_LINE.trim() }) {
            println("[remote-plugin] 系统 SSH 配置已包含 Gradle Remote Plugin 引用")
            return
        }
        
        val pluginBlock = buildString {
            appendLine(PLUGIN_COMMENT_START)
            appendLine(PLUGIN_COMMENT_WARN)
            appendLine(PLUGIN_INCLUDE_LINE)
            appendLine()
        }
        
        writeConfigAtomically(systemConfig, pluginBlock + existingContent)
        println("[remote-plugin] 已将 Gradle Remote Plugin 配置引用注入到 ~/.ssh/config")
    }

    private fun ensureSshDirAndConfigExists(sshDir: File, config: File) {
        if (!sshDir.exists()) {
            sshDir.mkdirs()
            setUnixPermissions(sshDir, "700")
        }
        if (!config.exists()) {
            config.createNewFile()
            setUnixPermissions(config, "600")
        }
    }

    private fun setUnixPermissions(file: File, perms: String) {
        if (!RemotePluginUtils.isWindows()) {
            try {
                when (perms) {
                    "700" -> {
                        file.setReadable(false, false); file.setReadable(true, true)
                        file.setWritable(false, false); file.setWritable(true, true)
                        file.setExecutable(false, false); file.setExecutable(true, true)
                    }
                    "600" -> {
                        file.setReadable(false, false); file.setReadable(true, true)
                        file.setWritable(false, false); file.setWritable(true, true)
                        file.setExecutable(false, false)
                    }
                }
            } catch (e: Exception) { /* ignore */ }
        }
    }

    private fun writeConfigAtomically(file: File, content: String) {
        val tempFile = File(file.parentFile, "${file.name}.tmp")
        try {
            tempFile.writeText(content)
            setUnixPermissions(tempFile, "600")
            tempFile.renameTo(file)
        } finally {
            if (tempFile.exists()) tempFile.delete()
        }
    }
    
    /**
     * 确保插件管理配置包含当前项目
     * 采用“影子解析配置”策略：将项目配置中的占位符解析后存入本地，确保 Terminal 和 Gradle 都能无感使用
     */
    private fun ensureManagedConfigIncludesProject(
        projectRootDir: File,
        projectName: String,
        projectSshConfig: File
    ) {
        val userHome = System.getProperty("user.home")
        val pluginConfigDir = File(userHome, ".ssh/gradle/remote-plugin")
        val resolvedDir = File(pluginConfigDir, "projects")
        val managedConfig = File(pluginConfigDir, "config")
        
        if (!resolvedDir.exists()) resolvedDir.mkdirs()
        
        val pathHash = Integer.toHexString(projectRootDir.absolutePath.hashCode())
        val resolvedProjectConfig = File(resolvedDir, "${projectName}-${pathHash}.config")
        
        try {
            val originalContent = projectSshConfig.readText()
            val resolvedContent = originalContent.replace("\${RP_PROJECT_ROOT_PATH}", projectRootDir.absolutePath)
            
            resolvedProjectConfig.writeText("# Auto-generated from: ${projectSshConfig.absolutePath}\n$resolvedContent")
            setUnixPermissions(resolvedProjectConfig, "600")
        } catch (e: Exception) {
            println("[remote-plugin] [WARN] 无法生成解析后的 SSH 配置: ${e.message}")
            return
        }
        
        val projectIncludeLine = "Include ${resolvedProjectConfig.absolutePath}"
        val existingContent = if (managedConfig.exists()) managedConfig.readText() else ""
        
        if (existingContent.lines().any { it.trim() == projectIncludeLine.trim() }) return
        
        val projectBlock = buildString {
            if (existingContent.isEmpty()) {
                appendLine(MANAGED_CONFIG_HEADER)
                appendLine(MANAGED_CONFIG_NOTE)
                appendLine()
            } else if (existingContent.isNotBlank()) {
                appendLine()
            }
            appendLine("# Project: $projectName")
            appendLine("# Path: ${projectRootDir.absolutePath}")
            appendLine(projectIncludeLine)
        }
        
        writeConfigAtomically(managedConfig, existingContent + projectBlock)
        println("[remote-plugin] 已将项目 SSH 配置（解析版）添加到插件管理配置中")
    }
}
